// Osogbo + Ire templates merged
export const EXTRA_TEMPLATES = {
  "osogbo:iku": "Prioriza la vida y la cabeza (ori): señales de alarma, pausa riesgos, chequeo médico y resguardo espiritual.",
  "osogbo:arun": "Enfermedad por dentro: valoración médica, descanso, dieta ligera y limpieza suave (baños/rezos).",
  "osogbo:ano": "Enfermedad por fuera: revisa piel/huesos; higiene, tratamiento tópico y protección diaria.",
  "osogbo:eyo": "Tragedia: plan de crisis, red de apoyo y reducir exposición a riesgos mientras estabilizas.",
  "osogbo:araye": "Problemas y disgustos: discreción, límites sanos, comunicaciones por escrito y evidencia de hechos.",
  "osogbo:inya": "Candela/golpes/guerras: desescalar, evitar confrontaciones y activar protecciones (tierra/agua).",
  "osogbo:akoba": "Imprevisto dañino: contingencias (ahorro/seguros), evita viajes/decisiones arriesgadas y revisa agenda.",
  "osogbo:afitibo": "Muerte de repente: máxima prudencia, evitar excesos, señales de alarma y acompañamiento cercano.",
  "osogbo:ofo": "Pérdidas/divorcios: inventario y copias, restitución si hay deuda, acuerdos claros; abre caminos con Eleguá.",
  "osogbo:ogu": "Brujería en general: limpieza, rezos y prohibiciones temporales; no entres en represalia.",
  "osogbo:elenu": "Por lenguas: silencio estratégico, no alimentar chismes, todo por escrito y testigos cuando proceda.",
  "osogbo:akala kambuca": "Hechicería de muerto/palería: protección reforzada, ofrendas acordes y evitar escaladas.",
  "osogbo:ashelu": "Justicia/tribunales: orden legal, asesoría profesional, puntualidad y evidencia organizada.",
  "osogbo:ona": "Caminos truncados/golpes: simplifica trámites, ruta alternativa, pequeño avance cada día; abre caminos.",
  "osogbo:egba": "Parálisis (cuerpo/parte): atención médica/fisioterapia, micro-movimientos y delegar tareas cruciales.",
  "osogbo:ofunshe-afoshe": "Polvos malos: higiene de espacios, barrido de umbrales y protección en entradas/salidas.",
  "osogbo:shepe": "Maldición: corta pactos verbales, declara tu palabra limpia y repara donde corresponda.",
  "osogbo:epe": "Maldición (variante): corta pactos verbales, afirma límites y limpia tu nombre con hechos.",
  "osogbo:tiya tiya": "Chismes/mal humor: pausa la reacción, hechos verificables y límites; reencuadre emocional.",
  "osogbo:oshishe": "Problemas de trabajo: higiene de agenda, prioriza, documenta y conversa a tiempo con superiores.",
  "osogbo:oran": "Delito/error propio: asume responsabilidad, repara el daño y consulta asesoría legal si aplica.",
  "osogbo:ewon": "Encarcelamiento: asesoría legal inmediata, cumple normas estrictas y activa red familiar.",
  "osogbo:eshe": "Aflicciones: apoyo emocional, descanso programado, micro-hábitos y oración/respiración.",
  "osogbo:ta eye": "Riesgo de sangre: evita objetos/ambientes riesgosos, protocolos de seguridad y desescalada.",
  "osogbo:aruy e": "Susto: enraizamiento (respiración/agua), revisión médica si hay síntomas y ritmo más lento.",
  "osogbo:aruye": "Susto: enraizamiento (respiración/agua), revisión médica si hay síntomas y ritmo más lento.",
  "osogbo:obesebi": "Fracaso: aprende rápido, pivota, plan B y metas pequeñas con feedback frecuente.",
  "osogbo:ekete niwa ile": "Conflictos con la casa: mantenimiento preventivo, arreglos urgentes, seguros y límites con vecinos.",
  "osogbo:omu": "Celos: comunicación honesta, límites, pausa redes y acuerdos claros; cuida la palabra.",
  "osogbo:osoku": "Riesgo de suicidio: prioriza seguridad y ayuda profesional inmediata; comparte carga con apoyo cercano.",
  "osogbo:onanlora": "Mal momento: reduce carga, apóyate en lo esencial y plan de 1–2 semanas con descanso.",
  "osogbo:aiyan": "Ansiedad: higiene del sueño, menos estimulantes, respiración cíclica y apoyo terapéutico.",
  "ire:ashegun ota": "Vences dificultades: mantén disciplina, pide consejo a mayores y consolida lo que está funcionando.",
  "ire:ashegun ota kolekio adio": "Vences dificultades y enemigos: prudencia, discreción y proteger planes hasta consolidar.",
  "ire:aiku": "Salud y longevidad: chequeo preventivo, descanso y hábitos sostenibles de energía.",
  "ire:omia": "Inteligencia: estudiar, escribir y tomar decisiones estratégicas guiadas por datos.",
  "ire:mota ari": "Lotería/azar: evita excesos; usa la fortuna para saldar deudas y crear un fondo.",
  "ire:owo": "Dinero: ordena presupuesto, invierte poco a poco y evita gastos impulsivos.",
  "ire:obale": "Poder/autoridad: usa la influencia con justicia, delega y documenta.",
  "ire:abiti irina": "Escapar de trampas: revisa contratos, pide segunda opinión y no firmes con presión.",
  "ire:shaie": "Momento oportuno: aprovecha ventanas cortas, ejecuta lo simple primero.",
  "ire:ike siwawi": "Progreso: pequeños pasos diarios medibles; elimina lo que no suma.",
  "ire:awe iku": "Burlar la muerte: celebra la vida con prudencia; cuida riesgos y agradece.",
  "ire:olo owe": "Sabiduría: escuchar antes de hablar; integra lecciones antiguas a la práctica actual.",
  "ire:oniwe": "Memoria: registra procesos, checklist y repetición espaciada.",
  "ire:loshowon": "Negocios/comercio: flujo de caja, márgenes y atención al cliente.",
  "ire:oya enimo": "Videncia espiritual: purifica la cabeza (ori), silencio y claridad de intención.",
  "ire:fishe tire": "Estabilidad: equilibrio entre ganancias y pérdidas; evita extremos.",
  "ire:dole waniolokun": "Del mar a la tierra: oportunidades externas que llegan; adapta operaciones.",
  "ire:betansi": "Bondad: actos de servicio, buen nombre y reciprocidad.",
  "ire:awe tebalaye": "En el aire: noticias/mensajes; verifica fuentes antes de actuar.",
  "ire:nisideni": "Puede perjudicar: evalúa costos ocultos; si no suma, declínalo con respeto.",
  "ire:ala jere": "Bien lejos: oportunidades a distancia; usa canales digitales/viaje planificado.",
  "ire:eleyo": "Por el día: agenda trámites y decisiones en horario diurno.",
  "ire:evar": "Por la noche: proteger descanso; tareas creativas o de análisis nocturno moderado.",
  "ire:oshonkoleto": "Resguardo: refuerza seguros, respaldos y copias de seguridad.",
  "ire:esu lokun": "Cruzar el mar: papeleo migratorio/logístico listo; mentoría internacional.",
  "ire:abiona": "Caminos abiertos: define meta y primer paso en 24h; evita dispersión.",
  "ire:lona ire": "Buenos caminos: elige la ruta de menor fricción que te acerca al objetivo.",
  "ire:lafafia": "Felicidad: gratitud diaria, tiempo con familia y descanso reparador.",
  "ire:waniotolokun": "Orilla del mar: transición; no te precipites, observa mareas antes de entrar.",
  "ire:omida": "Libertad: paga deudas, simplifica compromisos y protege tu tiempo.",
  "ire:omo": "Hijo/hijos: plan familiar, soporte y límites amorosos.",
  "ire:aye": "De todo: balancea áreas (salud, dinero, amor) con metas pequeñas por semana.",
  "ire:ile unisinishe": "Obtener trabajo: prepara CV, práctica de entrevista y referencias.",
  "ire:bawa ile": "Viene a la casa: mejora del hogar, orden y limpieza profunda.",
  "ire:silemu": "Inmune al peligro: mantén prudencia sin bajar guardia; evitar provocaciones.",
  "ire:kirin kirin": "Viaje: plan de ruta, seguro y documentos; evita gastos sorpresa.",
  "ire:ni buyoko": "Asentamiento: formaliza contratos, residencia o negocio.",
  "ire:otomowa": "Del cielo: reconocer regalos/ayuda; agradecer y compartir.",
  "ire:ota": "Por una piedra: base firme; usa herramientas/recursos concretos.",
  "ire:oshe ire": "Buenas acciones: continúa obras de bien; el mérito abre puertas.",
  "ire:ayo": "Alegría: celebra sin excesos; comparte con prudencia.",
  "ire:eniron": "Videncia espiritual: silencio y limpieza de pensamiento antes de decidir.",
  "ire:alakiyo": "Ángel de la guarda: obedecer señales, oración y equilibrio emocional.",
  "ire:decie wan": "De todo un poco: gestión integral; prioriza lo crítico y agenda revisiones.",
  "ire:abbilona": "Caminos muy abiertos: define tres metas y primer paso hoy.",
  "ire:bata": "Festejo: compartir con moderación; no anunciar todo públicamente.",
  "ire:abeyawo": "Matrimonio: acuerdos claros, respeto y proyecto común.",
  "ire:oshinshe": "Trabajo: enfoque en tareas de alto impacto; pide feedback.",
  "ire:alaleyo": "Acompañamiento del ángel de la guarda: refuerza tu práctica devocional."
};
